### PR TITLE
Added changelog parameter to sepc file

### PR DESCRIPTION
**Pull request by FrankCRoth**

### CODE REVIEW

**Comment by kevinconway** [comment]
Hey, sorry for the delay. I've been traveling without a laptop or Internet access for a bit.

The change has a small surface area and fits within an already tested feature. You shouldn't need to change anything unless a style gate fails in ci. I'd recommend rebasing the change onto the latest HEAD. We recently added some new tests and updated the Travis config. If you do that and everything goes green then I'll be happy to cut a new rev and publish this change.

**Comment by FrankCRoth** [comment]
Hi Kevin, no problem. Was just wondering if you need anything else. Otherwise useful module for building rpm packages.

**Comment by kevinconway** [comment]
Had some extra time today so I pulled out your branch, rebased it on the latest HEAD, and ran the test suite. Everything looks good so I'm going to merge. Will comment again when the change is released.

**Comment by kevinconway** [comment]
OK, your change is now published as part of `0.17.0` on PyPi. Thanks again for the contribution. I apologize that it took so long to get this through.

**Comment by FrankCRoth** [comment]
Hi Kevin,

thx a lot. Don’t worry about the timing. Good work.

Cheers,

Frank

**Pull request merged**
