### PR TITLE
fixed: return code is 0 on success

### PR DESCRIPTION
**Pull request by joaoubaldo**
This will fix https://github.com/kevinconway/rpmvenv/issues/21

### CODE REVIEW

**Comment by kevinconway** [comment]
Thanks a bunch for finding this bug and submitting a patch. I'm surprised this went unnoticed for so long.

It looks like the test is failing because of an error in the way I wrote the test. Would you mind fixing the test with this commit so everything is green before it goes in? It should be a small change to https://github.com/kevinconway/rpmvenv/blob/master/tests/test_cli.py#L17. For example:

```python
def test_python_cmd_build(python_source_code, python_config_file):
    """Test that a default build works without exception."""
    with pytest.raises(SystemExit) as exc:
        cli.main((python_config_file, '--source', python_source_code))
    assert exc.code == 0
```

If you also bump the version in `setup.py` to '0.10.0' I can ship this to PyPI right after merge as well.

**Comment by joaoubaldo** [comment]
I think this is fine now. I don't particularly like the test solution I came up with, but it's working on every tested python version.

**Comment by kevinconway** [comment]
That's an odd pytest bug you've found there... I'm comfortable rolling with this patch for now. I'll spend some cycles trying to figure out why you had to account for a difference in PY2.6 when I have them.

Thanks again for reporting the bug and posting a fix for it!

**Comment by kevinconway** [comment]
Your patch is deployed to PyPi under version 0.10.0 now.

**Comment by joaoubaldo** [comment]
Great!

**Pull request merged**
