### PR TITLE
ensuring defattr is inserted at the beginning of the files block

### PR DESCRIPTION
**Pull request by ariens**
Performs insert at position 0 instead of append.

### CODE REVIEW

**Comment by ariens** [comment]
Not sure why this test would have failed... Please advise what's required for me to get this pulled...

**Comment by kevinconway** [comment]
Hi there!

The tests are failing the PyFlakes linter. If you run tox it should give you some more details. I believe it's because you've placed one argument in-line with the function call and another after a vertical break. It wants one or the other. For example, this should work without failing the style gate:

```python
spec.blocks.files.insert(
    0,
    '%defattr(-,%{file_permissions_user},%{file_permissions_group},-)',
)
```

**Comment by ariens** [comment]
@kevinconway fixed up!  I'm new to tox, can you help me better understand how I can run it locally and reproduce the results that Travis CI arrived at?  Alongside my cloned rpmvenv repo I created a Python 3.4 virtual environment in which I installed tox (2.3.1).  I activated that venv, then entered into my rpmvenv project, and executed `tox --skip-missing-interpreters`. 

Promisingly, py27 succeeded: `platform linux2 -- Python 2.7.6, pytest-3.0.3, py-1.4.31, pluggy-0.4.0` passed 13/13 items, however Python 3.4 was a different story.

There was the RPM artifact from the py27 env that broke the subsequent py34 testing (`shutil.Error: Destination path './test-pkg-1.2.3.4-1.x86_64.rpm' already exists`) and pylint complained about spelling, options, and an InvocationError:

```
This option 'required-attributes' will be removed in Pylint 2.0This option 'ignore-iface-methods' will be removed in Pylint 2.0ERROR: InvocationError: '/home/dariens/projects/python/rpmvenv/.tox/pylint/bin/pylint --rcfile=.pylintrc rpmvenv/'
```

Here's my summary (when I omit py27 from tox.ini):

```
  py34: commands succeeded
  pep8: commands succeeded
  pyflakes: commands succeeded
ERROR:   pylint: commands failed
```

I'm assuming the tox version on Travis is different or your and/or there is configuration within the Travis CI service that I am missing...

**Comment by kevinconway** [comment]
The issue you're hitting with tox is not actually tox's fault. When I originally wrote the tests I had them use the current working directory as the place to put test artifacts. Tox is doing what it's supposed to, running the tests under multiple versions of Python, but the tests are misbehaving and leaving stale data around. Another contributor has a patch in to resolve it.

Travis doesn't hit the issue because we don't use tox when testing there. Travis let's us set up a test matrix through the YAML config so tox isn't needed to do the same thing. The Travis tests also don't run PyLint. I'm a big fan of PyLint, but I don't use it as a test gate. It's there to give feedback to the developer and help make good choices but it is not a source of truth.

As far as the patch goes, I believe putting the defattr at the beginning of the FILES block is the correct thing to do. Looks good to me.

**Pull request merged**
