### PR TITLE
Fixes for native modules

### PR DESCRIPTION
**Pull request by tlusk**

### CODE REVIEW

**Comment by kevinconway** [comment]
Hey! Thanks for putting in a patch. It's always nice to see a contribution to the project.

Looks like the patch passes what tests we have for the project. Before I merge, would you please give me some details on the change? I'm curious what scenario exposed the bug for you and what consequences you think there might be for striping native modules from the package. Also, if you can point to a publicly available repo that I can point the build tests at to repro then I can add a regression test to make sure future changes don't cause your issue again.

**Comment by tlusk** [comment]
Two commits in this, first one to strip buildroot paths from native modules fixes an issue where `QA_SKIP_BUILD_ROOT=1` needed to be set if the requirements.txt file included any modules that built native libraries (with *.so files).  That's because the debug information that is built into the libraries contains the buildroot path.  Stripping all the *.so files removes the extra unneeded information and allows it to be run without exporting that variable.  I found just having a requirements file with python-cjson was enough to cause it (anything that generates a so lib)

The second commit fixes an issue where you would get `unpacking of archive failed...MD5 sum mismatch` when trying to install the generated rpm.  At least in my case the only thing I needed to do to reproduce it on CentOS 6 was to have prelink installed.  It has something to do with the fact that the python executable that is being copied into the RPM is already prelinked, and the rpm build generates an md5 and then un-prelinks it after the md5 is generated causing the hash to mismatch. I've seen the workaround of disabling prelink undo in a couple other rpm spec files that deal with virtualenvs in order to deal with this problem.

**Comment by kevinconway** [comment]
Thanks! That explanation is very useful. I made a ticket to remind myself, eventually, to add a test case that recreates your scenario so we can catch regressions in the future.

**Comment by kevinconway** [comment]
I've uploaded a new version "0.12.0" to PyPi with your patch. Thanks again!

**Pull request merged**
